# =========================
# Experiment Config: OpenBG-IMG Text-Only
# =========================

dataset:
  name: openbg_img
  train: data/datasets/openbg_img/raw/OpenBG-IMG_train.tsv
  dev: data/datasets/openbg_img/raw/OpenBG-IMG_dev.tsv
  test: data/datasets/openbg_img/raw/OpenBG-IMG_test.tsv
  cache_dir: data/cache/openbg_img
  cache_format: auto

model:
  name: openbg_img_text_only
  num_relations: 136

training:
  lr: 0.0003
  img_dropout: 0.0

evaluation:
  chunk_size: 4096
  query_batch_size: 32

output:
  exp_name: openbg_img_text_only
